setting = 1
muPAR=10*0.665 # Second stage response rate of responders to A who preferred A
muRAR=10*0.615 # Second stage response rate of responders to A who were randomized A
muPBR=10*0.37 # Second stage response rate of responders to B who preferred B
muRBR=10*0.35 # Second stage response rate of responders to B who were randomized B
muPANRPC=10*0.675 # Second stage response rate of non-responders to prefer A who prefer C in the second stage
muPANRRC=10*0.645 # Second stage response rate of non-responders to prefer A who are randomized C in the second stage
muPANRPD=10*0.565 # Second stage response rate of non-responders to prefer A who prefer D in the second stage
muPANRRD=10*0.545  # Second stage response rate of non-responders to prefer A who are randomized D in the second stage
muRANRPC=10*0.625  # Second stage response rate of non-responders who were randomized A who preferred C in the second stage
muRANRRC=10*0.595 # Second stage response rate of non-responders who were randomized A who were randomized C in the second stage
muRANRPD=10*0.515 # Second stage response rate of non-responders who were randomized A who preferred D in the second stage
muRANRRD=10*0.465 # Second stage response rate of non-responders who were randomized A who were randomized D in the second stage
muPBNRPC=10*0.35 # Second stage response rate of non-responders to prefer B who prefer C in the second stage
muPBNRRC=10*0.32 # Second stage response rate of non-responders to prefer B who are randomized C in the second stage
muPBNRPD=10*0.24 # Second stage response rate of non-responders to prefer B who prefer D in the second stage
muPBNRRD=10*0.22 # Second stage response rate of non-responders to prefer B who are randomized D in the second stage
muRBNRPC=10*0.3 # Second stage response rate of non-responders who were randomized B who preferred C in the second stage
muRBNRRC=10*0.27 # Second stage response rate of non-responders who were randomized B who were randomized C in the second stage
muRBNRPD=10*0.19 # Second stage response rate of non-responders who were randomized B who preferred D in the second stage
muRBNRRD=10*0.17 # Second stage response rate of non-responders who were randomized B who were randomized D in the second stage